#!/bin/bash
if [[ `groups $USER` == *"docker"* ]]; then
 DOCKERGROUPED=1
fi

if [ ! -d "ctx" ];then
  echo "Run this script from the soflinux folder"
  exit 1
fi

if [ ! -d ~/.loki/sof ] ; then
  echo "Creating user directory at ~/.loki/sof..."
  #ensure mounted folders are created before-hand
  #so that permission is not unwriteable root.
  mkdir -p ~/.loki/sof
else
  if [ `stat --format '%U' ~/.loki/sof` = "root" ]; then
    echo "Your loki user directory is root-owned, this has to be changed"
    sudo chown -R $USER:$USER ~/.loki/sof
  fi
fi

# do the same for the base folder mount
if [ ! -d ~/.loki/sof-base ] ; then
  echo "Creating base directory at ~/.loki/sof-base..."
  echo "Use this for extra map .pak files and autoexec.cfg"
  mkdir -p ~/.loki/sof-base
else
  if [ `stat --format '%U' ~/.loki/sof-base` = "root" ]; then
    echo "Your loki base directory is root-owned, this has to be changed"
    sudo chown -R $USER:$USER ~/.loki/sof-base
  fi
fi

if [ ! -f ~/.loki/sof/default_video.cfg ]; then
  echo "Copying default_video.cfg fix into user dir..."
  cp ctx/default_video.cfg ~/.loki/sof/
  cp ctx/won_key ~/.loki/sof/
fi
# base folder on host, so that extra maps can be added
# user folder also on host, so that saves and downloads are persistent
if [ -z DOCKERGROUPED ]; then
  echo "Using sudo, becuase your user is not in docker group"
  TOSUDO=sudo
fi
$TOSUDO docker run -it \
--privileged \
--device /dev/dri \
--device /dev/snd \
--env XDG_RUNTIME_DIR=/run/mullins/1000 \
--env DISPLAY=$DISPLAY \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-v ~/.loki/sof-base:/home/mullins/sof/base \
-v ~/.loki/sof:/home/mullins/.loki/sof \
real /bin/bash
